# Generated by Django 4.2.7 on 2023-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pizza_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                ("rate", models.FloatField(default=0)),
                ("prepare_time", models.FloatField(blank=True, null=True)),
                ("calories", models.FloatField(blank=True)),
                ("price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
