# Generated by Django 4.2.7 on 2023-11-26 11:29

from django.db import migrations, models
import pizza.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, upload_to=pizza.models.upload_pizza_image),
        ),
    ]
