# Generated by Django 4.2.7 on 2023-12-02 07:17

from django.db import migrations, models
import pizza.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_burger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to=pizza.models.upload_burger_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='burger',
            name='image',
            field=models.ImageField(blank=True, upload_to=pizza.models.upload_burger_image),
        ),
    ]
