# Generated by Django 4.2.7 on 2023-12-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_restaurant_alter_burger_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pizza', to='pizza.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to=models.CharField(max_length=150)),
        ),
    ]
