# Generated by Django 4.2.7 on 2023-12-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_pizza_restaurant_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='burger', to='pizza.restaurant'),
            preserve_default=False,
        ),
    ]
