# Generated by Django 4.2.7 on 2023-12-03 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_burger_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burger',
            options={'ordering': ['pk'], 'verbose_name': 'BURGER', 'verbose_name_plural': 'Burgers'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['pk'], 'verbose_name': 'PIZZA', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.RemoveField(
            model_name='burger',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='burger',
            name='restaurant',
            field=models.ManyToManyField(related_name='burger', to='pizza.restaurant'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='restaurant',
            field=models.ManyToManyField(related_name='pizza', to='pizza.restaurant'),
        ),
    ]
