# Generated by Django 4.2.7 on 2023-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_alter_burger_options_alter_pizza_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['restaurant_name'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.RemoveField(
            model_name='burger',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='burgers',
            field=models.ManyToManyField(blank=True, related_name='burger', to='pizza.burger'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pizzas',
            field=models.ManyToManyField(blank=True, related_name='pizza', to='pizza.pizza'),
        ),
    ]
